create TABLE ${flyway:defaultSchema}.footballers
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(255)                             NOT NULL,
    second_name VARCHAR(255)                             NOT NULL,
    sex         VARCHAR(255)                             NOT NULL,
    birthday    date                                     NOT NULL,
    team_name   VARCHAR(255)                             NOT NULL,
    country     VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_footballers PRIMARY KEY (id)
);